name: Test renovate.json
on:
  push:
    paths:
      - '.github/renovate.json'

jobs:
  test_suite:
    runs-on: ubuntu-latest
    name: Test Renovate Config
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Install renovate
        run: npm install renovate -g
      - name: Run Test
        run: npx renovate-config-validator
